name: Build and Deploy
on: [ push, pull_request ]

permissions:
  contents: write

env:
  RELEASES_REPO: berkchy/phantom-releases

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle
      - name: Build and Sign APK
        env:
          KEYSTORE_FILE_PATH: ${{ github.workspace }}/signingkey.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          if [[ -n "${{ secrets.SIGNING_KEY }}" ]]; then
            echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > ${{ env.KEYSTORE_FILE_PATH }}
            ./gradlew assembleGitContinuous
            mv app/build/outputs/apk/git/continuous/app-git-continuous.apk CS16Client-Android.apk
          else
            ./gradlew assembleGitDebug
            mv app/build/outputs/apk/git/debug/app-git-debug.apk CS16Client-Android.apk
          fi
        working-directory: android
      - name: Upload release asset
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          repository: ${{ env.RELEASES_REPO }}
          token: ${{ secrets.RELEASES_TOKEN }}
          tag_name: ${{ github.ref_name == 'main' && 'continuous' || format('continuous-{0}', github.ref_name) }}
          files: android/CS16Client-Android.apk
          fail_on_unmatched_files: true
          overwrite_files: true
  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [ 'x86', 'amd64' ]
      fail-fast: false
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup Visual Studio
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Configure
        run: cmake --preset "win32-ci-${{ matrix.arch }}"
      - name: Build and Package
        run: |
          cmake --build .
          cpack --config CPackConfig.cmake
        working-directory: build
      - name: Upload release asset
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          repository: ${{ env.RELEASES_REPO }}
          token: ${{ secrets.RELEASES_TOKEN }}
          tag_name: ${{ github.ref_name == 'main' && 'continuous' || format('continuous-{0}', github.ref_name) }}
          files: build/*.zip
          fail_on_unmatched_files: true
          overwrite_files: true
